name: Python application CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: "ghcr.io/audeldiaz-work"
  IMAGE_NAME: "github-actions-lab"

permissions:
  packages: write
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.${{ vars.PYTHON_MINOR_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: "3.${{ vars.PYTHON_MINOR_VERSION }}"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest coverage
          if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          coverage run -m pytest
          coverage report -m

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./
          file: Dockerfile.actions
          pull: true
          build-args: |
            PYTHON_VERSION=3.${{ vars.PYTHON_MINOR_VERSION }}
          tags: |
            "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
            "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          format: "sarif"
          output: "trivy-results.sarif"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Or your PAT secret

      - name: push image to ghcr.io
        run: docker push ghcr.io/audeldiaz-work/github-actions-lab --all-tags
